name: bevideo
description: A new Flutter project.
author: Steeve DevOps
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^3.1.0
  flutter_feather_icons: ^2.0.0+1
  bestapp_package:
    path: ../bestapp_package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/images/
    - lib/assets/logos/
    - lib/assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
